POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username" : "user",
  "password" : "1111"
}

### 첫번쨰

POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username" : "manager",
  "password" : "1111"
}

### 두번쨰
POST http://localhost:8080/api/messages
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### 세번쨰